### ISSUE TITLE
blynklib.py license

### ISSUE THREAD

**Issue by matsujirushi** [shillehbean/youtube-channel#2]
Hi,

I am planning to use blynklib.py.
Could you upload a LICENSE file so we can check the license?

https://github.com/shillehbean/youtube-channel/blob/10b320ca7849304111fd70dd80570aeebae5015d/blynklib.py#L1C56-L1C69

**Comment by shillehbean** [comment]
This file is actually from Blynk the company and its open source I believe, I wouldn't worry about that

**Comment by matsujirushi** [comment]
Thanks!
